"""Catálogos oficiales estáticos (sin base de datos).

- DIVIPOLA (DANE): los 33 departamentos y los 1.122 municipios oficiales, con sus
  códigos reales (2 dígitos el departamento, 5 el municipio).
- CIIU Rev. 4 A.C. (DANE): 21 secciones (A-U), 88 divisiones y ~106 clases de uso
  frecuente. El total oficial de clases es 486; la cobertura cargada se reporta en
  GET /api/catalogos/ciiu/estructura.
- Catálogos operativos por defecto (tipo de inmueble, contrato, documento, etc.),
  sobreescribibles por tenant vía la tabla configuraciones_operativas.
"""

# ---------------------------------------------------------------------------
# DIVIPOLA · [(cod_depto, nombre_depto, [(cod_municipio, nombre_municipio), ...])]
# El catálogo completo del DANE vive en divipola_completo.py (archivo generado).
# ---------------------------------------------------------------------------
from app.catalogos.divipola_completo import DIVIPOLA  # noqa: E402  (re-exportado)

DEPARTAMENTOS: list[dict] = [{"cod": d[0], "nombre": d[1]} for d in DIVIPOLA]
MUNICIPIOS: dict[str, list[dict]] = {
    d[0]: [{"cod": m[0], "nombre": m[1]} for m in d[2]] for d in DIVIPOLA
}

# ---------------------------------------------------------------------------
# CIIU Rev. 4 A.C. (DANE)
# ---------------------------------------------------------------------------
# (codigo_seccion, nombre, rango_divisiones)
CIIU_SECCIONES: list[tuple[str, str, str]] = [
    ("A", "Agricultura, ganadería, caza, silvicultura y pesca", "01-03"),
    ("B", "Explotación de minas y canteras", "05-09"),
    ("C", "Industrias manufactureras", "10-33"),
    ("D", "Suministro de electricidad, gas, vapor y aire acondicionado", "35-35"),
    ("E", "Distribución de agua; evacuación y tratamiento de aguas residuales, gestión de desechos", "36-39"),
    ("F", "Construcción", "41-43"),
    ("G", "Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas", "45-47"),
    ("H", "Transporte y almacenamiento", "49-53"),
    ("I", "Alojamiento y servicios de comida", "55-56"),
    ("J", "Información y comunicaciones", "58-63"),
    ("K", "Actividades financieras y de seguros", "64-66"),
    ("L", "Actividades inmobiliarias", "68-68"),
    ("M", "Actividades profesionales, científicas y técnicas", "69-75"),
    ("N", "Actividades de servicios administrativos y de apoyo", "77-82"),
    ("O", "Administración pública y defensa; planes de seguridad social de afiliación obligatoria", "84-84"),
    ("P", "Educación", "85-85"),
    ("Q", "Actividades de atención de la salud humana y de asistencia social", "86-88"),
    ("R", "Actividades artísticas, de entretenimiento y recreación", "90-93"),
    ("S", "Otras actividades de servicios", "94-96"),
    ("T", "Actividades de los hogares individuales como empleadores", "97-98"),
    ("U", "Actividades de organizaciones y entidades extraterritoriales", "99-99"),
]

# (codigo_division, seccion, nombre) · 88 divisiones
CIIU_DIVISIONES: list[tuple[str, str, str]] = [
    ("01", "A", "Agricultura, ganadería, caza y actividades de servicios conexas"),
    ("02", "A", "Silvicultura y extracción de madera"),
    ("03", "A", "Pesca y acuicultura"),
    ("05", "B", "Extracción de carbón de piedra y lignito"),
    ("06", "B", "Extracción de petróleo crudo y gas natural"),
    ("07", "B", "Extracción de minerales metalíferos"),
    ("08", "B", "Extracción de otras minas y canteras"),
    ("09", "B", "Actividades de servicios de apoyo para la explotación de minas y canteras"),
    ("10", "C", "Elaboración de productos alimenticios"),
    ("11", "C", "Elaboración de bebidas"),
    ("12", "C", "Elaboración de productos de tabaco"),
    ("13", "C", "Fabricación de productos textiles"),
    ("14", "C", "Confección de prendas de vestir"),
    ("15", "C", "Curtido y recurtido de cueros; calzado; artículos de viaje"),
    ("16", "C", "Transformación de la madera y fabricación de productos de madera y corcho"),
    ("17", "C", "Fabricación de papel, cartón y productos de papel y cartón"),
    ("18", "C", "Actividades de impresión y de producción de copias"),
    ("19", "C", "Coquización, fabricación de productos de la refinación del petróleo"),
    ("20", "C", "Fabricación de sustancias y productos químicos"),
    ("21", "C", "Fabricación de productos farmacéuticos, sustancias químicas medicinales"),
    ("22", "C", "Fabricación de productos de caucho y de plástico"),
    ("23", "C", "Fabricación de otros productos minerales no metálicos"),
    ("24", "C", "Fabricación de productos metalúrgicos básicos"),
    ("25", "C", "Fabricación de productos elaborados de metal"),
    ("26", "C", "Fabricación de productos informáticos, electrónicos y ópticos"),
    ("27", "C", "Fabricación de aparatos y equipo eléctrico"),
    ("28", "C", "Fabricación de maquinaria y equipo n.c.p."),
    ("29", "C", "Fabricación de vehículos automotores, remolques y semirremolques"),
    ("30", "C", "Fabricación de otros tipos de equipo de transporte"),
    ("31", "C", "Fabricación de muebles, colchones y somieres"),
    ("32", "C", "Otras industrias manufactureras"),
    ("33", "C", "Instalación, mantenimiento y reparación especializado de maquinaria y equipo"),
    ("35", "D", "Suministro de electricidad, gas, vapor y aire acondicionado"),
    ("36", "E", "Captación, tratamiento y distribución de agua"),
    ("37", "E", "Evacuación y tratamiento de aguas residuales"),
    ("38", "E", "Recolección, tratamiento y disposición de desechos"),
    ("39", "E", "Actividades de saneamiento ambiental y otros servicios de gestión de desechos"),
    ("41", "F", "Construcción de edificios"),
    ("42", "F", "Obras de ingeniería civil"),
    ("43", "F", "Actividades especializadas para la construcción de edificios y obras de ingeniería civil"),
    ("45", "G", "Comercio, mantenimiento y reparación de vehículos automotores y motocicletas"),
    ("46", "G", "Comercio al por mayor, excepto el de vehículos automotores"),
    ("47", "G", "Comercio al por menor, excepto el de vehículos automotores"),
    ("49", "H", "Transporte terrestre; transporte por tuberías"),
    ("50", "H", "Transporte acuático"),
    ("51", "H", "Transporte aéreo"),
    ("52", "H", "Almacenamiento y actividades complementarias al transporte"),
    ("53", "H", "Correo y servicios de mensajería"),
    ("55", "I", "Alojamiento"),
    ("56", "I", "Actividades de servicios de comidas y bebidas"),
    ("58", "J", "Actividades de edición"),
    ("59", "J", "Actividades cinematográficas, de video y producción de programas de televisión"),
    ("60", "J", "Actividades de programación, transmisión y/o difusión"),
    ("61", "J", "Telecomunicaciones"),
    ("62", "J", "Desarrollo de sistemas informáticos, consultoría y actividades relacionadas"),
    ("63", "J", "Actividades de servicios de información"),
    ("64", "K", "Actividades de servicios financieros, excepto seguros y pensiones"),
    ("65", "K", "Seguros, reaseguros y fondos de pensiones"),
    ("66", "K", "Actividades auxiliares de las actividades de servicios financieros"),
    ("68", "L", "Actividades inmobiliarias"),
    ("69", "M", "Actividades jurídicas y de contabilidad"),
    ("70", "M", "Actividades de administración empresarial y de consultoría de gestión"),
    ("71", "M", "Actividades de arquitectura e ingeniería; ensayos y análisis técnicos"),
    ("72", "M", "Investigación científica y desarrollo"),
    ("73", "M", "Publicidad y estudios de mercado"),
    ("74", "M", "Otras actividades profesionales, científicas y técnicas"),
    ("75", "M", "Actividades veterinarias"),
    ("77", "N", "Actividades de alquiler y arrendamiento"),
    ("78", "N", "Actividades de empleo"),
    ("79", "N", "Agencias de viajes y operadores turísticos"),
    ("80", "N", "Actividades de seguridad e investigación privada"),
    ("81", "N", "Actividades de servicios a edificios y paisajismo"),
    ("82", "N", "Actividades administrativas y de apoyo de oficina"),
    ("84", "O", "Administración pública y defensa; planes de seguridad social de afiliación obligatoria"),
    ("85", "P", "Educación"),
    ("86", "Q", "Actividades de atención de la salud humana"),
    ("87", "Q", "Actividades de atención residencial medicalizada"),
    ("88", "Q", "Actividades de asistencia social sin alojamiento"),
    ("90", "R", "Actividades creativas, artísticas y de entretenimiento"),
    ("91", "R", "Actividades de bibliotecas, archivos, museos y otras actividades culturales"),
    ("92", "R", "Actividades de juegos de azar y apuestas"),
    ("93", "R", "Actividades deportivas y actividades recreativas y de esparcimiento"),
    ("94", "S", "Actividades de asociaciones"),
    ("95", "S", "Mantenimiento y reparación de computadores, efectos personales y enseres domésticos"),
    ("96", "S", "Otras actividades de servicios personales"),
    ("97", "T", "Actividades de los hogares individuales como empleadores de personal doméstico"),
    ("98", "T", "Actividades no diferenciadas de los hogares individuales como productores de bienes y servicios para uso propio"),
    ("99", "U", "Actividades de organizaciones y entidades extraterritoriales"),
]

# (codigo_clase_4_digitos, descripcion) · clases de uso frecuente
CIIU_CLASES: list[tuple[str, str]] = [
    ("0111", "Cultivo de cereales (excepto arroz), legumbres y semillas oleaginosas"),
    ("0113", "Cultivo de hortalizas, raíces y tubérculos"),
    ("0121", "Cultivo de frutas tropicales y subtropicales"),
    ("0127", "Cultivo de plantas con las que se preparan bebidas (café, cacao)"),
    ("0141", "Cría de ganado bovino y bufalino"),
    ("0145", "Cría de aves de corral"),
    ("0161", "Actividades de apoyo a la agricultura"),
    ("0510", "Extracción de hulla (carbón de piedra)"),
    ("0610", "Extracción de petróleo crudo"),
    ("0710", "Extracción de minerales de hierro"),
    ("0910", "Actividades de apoyo para la extracción de petróleo y de gas natural"),
    ("1011", "Procesamiento y conservación de carne y productos cárnicos"),
    ("1081", "Elaboración de productos de panadería"),
    ("1104", "Elaboración de bebidas no alcohólicas"),
    ("1410", "Confección de prendas de vestir, excepto prendas de piel"),
    ("1512", "Fabricación de artículos de viaje, bolsos de mano y artículos similares"),
    ("1521", "Fabricación de calzado de cuero y piel"),
    ("2011", "Fabricación de sustancias y productos químicos básicos"),
    ("2100", "Fabricación de productos farmacéuticos y medicamentos"),
    ("2229", "Fabricación de artículos de plástico n.c.p."),
    ("2599", "Fabricación de otros productos elaborados de metal n.c.p."),
    ("3110", "Fabricación de muebles"),
    ("3511", "Generación de energía eléctrica"),
    ("3600", "Captación, tratamiento y distribución de agua"),
    ("3811", "Recolección de desechos no peligrosos"),
    ("4111", "Construcción de edificios residenciales"),
    ("4112", "Construcción de edificios no residenciales"),
    ("4210", "Construcción de carreteras y vías de ferrocarril"),
    ("4321", "Instalaciones eléctricas"),
    ("4330", "Terminación y acabado de edificios y obras de ingeniería civil"),
    ("4511", "Comercio de vehículos automotores nuevos"),
    ("4520", "Mantenimiento y reparación de vehículos automotores"),
    ("4530", "Comercio de partes, piezas (autopartes) y accesorios para vehículos"),
    ("4631", "Comercio al por mayor de productos alimenticios"),
    ("4641", "Comercio al por mayor de productos textiles y prendas de vestir"),
    ("4645", "Comercio al por mayor de productos farmacéuticos y odontológicos"),
    ("4651", "Comercio al por mayor de computadores y equipo de telecomunicaciones"),
    ("4711", "Comercio al por menor en establecimientos no especializados con surtido de alimentos"),
    ("4719", "Comercio al por menor en establecimientos no especializados"),
    ("4741", "Comercio al por menor de computadores y equipos de telecomunicaciones"),
    ("4771", "Comercio al por menor de prendas de vestir y sus accesorios"),
    ("4772", "Comercio al por menor de todo tipo de calzado y artículos de cuero"),
    ("4773", "Comercio al por menor de productos farmacéuticos y medicinales"),
    ("4791", "Comercio al por menor realizado a través de internet"),
    ("4921", "Transporte de pasajeros"),
    ("4923", "Transporte de carga por carretera"),
    ("5111", "Transporte aéreo nacional de pasajeros"),
    ("5210", "Almacenamiento y depósito"),
    ("5320", "Actividades de mensajería"),
    ("5511", "Alojamiento en hoteles"),
    ("5611", "Expendio a la mesa de comidas preparadas"),
    ("5613", "Expendio de comidas preparadas en cafeterías"),
    ("5630", "Expendio de bebidas alcohólicas para el consumo dentro del establecimiento"),
    ("5811", "Edición de libros"),
    ("5911", "Actividades de producción de películas y videos"),
    ("6010", "Actividades de programación y transmisión en el servicio de radiodifusión sonora"),
    ("6110", "Actividades de telecomunicaciones alámbricas"),
    ("6120", "Actividades de telecomunicaciones inalámbricas"),
    ("6201", "Actividades de desarrollo de sistemas informáticos (planificación, análisis, diseño, programación, pruebas)"),
    ("6202", "Actividades de consultoría informática y actividades de administración de instalaciones informáticas"),
    ("6209", "Otras actividades de tecnologías de información y actividades de servicios informáticos"),
    ("6311", "Procesamiento de datos, alojamiento (hosting) y actividades relacionadas"),
    ("6412", "Bancos comerciales"),
    ("6424", "Actividades financieras de fondos de empleados y otras formas asociativas"),
    ("6512", "Seguros generales"),
    ("6611", "Administración de mercados financieros"),
    ("6612", "Corretaje de valores y de contratos de productos básicos"),
    ("6810", "Actividades inmobiliarias realizadas con bienes propios o arrendados"),
    ("6820", "Actividades inmobiliarias realizadas a cambio de una retribución o por contrata"),
    ("6910", "Actividades jurídicas"),
    ("6920", "Actividades de contabilidad, teneduría de libros, auditoría financiera y asesoría tributaria"),
    ("7010", "Actividades de administración empresarial"),
    ("7020", "Actividades de consultoría de gestión"),
    ("7110", "Actividades de arquitectura e ingeniería y otras actividades conexas de consultoría técnica"),
    ("7210", "Investigaciones y desarrollo experimental en el campo de las ciencias naturales y la ingeniería"),
    ("7310", "Publicidad"),
    ("7320", "Estudios de mercado y realización de encuestas de opinión pública"),
    ("7410", "Actividades especializadas de diseño"),
    ("7420", "Actividades de fotografía"),
    ("7500", "Actividades veterinarias"),
    ("7710", "Alquiler y arrendamiento de vehículos automotores"),
    ("7810", "Actividades de agencias de empleo"),
    ("7911", "Actividades de las agencias de viaje"),
    ("8010", "Actividades de seguridad privada"),
    ("8121", "Limpieza general interior de edificios"),
    ("8211", "Actividades combinadas de servicios administrativos de oficina"),
    ("8299", "Otras actividades de servicio de apoyo a las empresas n.c.p."),
    ("8411", "Actividades legislativas de la administración pública"),
    ("8521", "Educación básica primaria"),
    ("8530", "Establecimientos que combinan diferentes niveles de educación"),
    ("8543", "Educación de universidades"),
    ("8551", "Formación académica no formal"),
    ("8610", "Actividades de hospitales y clínicas, con internación"),
    ("8621", "Actividades de la práctica médica, sin internación"),
    ("8622", "Actividades de la práctica odontológica"),
    ("8891", "Actividades de cuidado diurno de niños"),
    ("9001", "Creación literaria"),
    ("9311", "Gestión de instalaciones deportivas"),
    ("9319", "Otras actividades deportivas"),
    ("9411", "Actividades de asociaciones empresariales y de empleadores"),
    ("9511", "Mantenimiento y reparación de computadores y de equipo periférico"),
    ("9602", "Peluquería y otros tratamientos de belleza"),
    ("9609", "Otras actividades de servicios personales n.c.p."),
    ("9700", "Actividades de los hogares individuales como empleadores de personal doméstico"),
    ("9900", "Actividades de organizaciones y entidades extraterritoriales"),
]

CIIU_TOTAL_OFICIAL = 486

# Sinónimos coloquiales para la búsqueda (portados del prototipo).
CIIU_SINONIMOS: dict[str, str] = {
    "6201": "software programacion desarrollo apps aplicaciones web sistemas informatica ingeniero de sistemas developer",
    "6202": "consultoria informatica soporte tecnico infraestructura ti",
    "6209": "tecnologia servicios informaticos datos",
    "6311": "hosting nube servidores datacenter",
    "5611": "restaurante comida asadero pizzeria comidas rapidas",
    "5613": "cafeteria cafe panaderia refrigerios",
    "5630": "bar licores discoteca",
    "4711": "tienda supermercado minimercado granero",
    "4719": "almacen miscelanea variedades",
    "4771": "ropa boutique almacen de ropa moda",
    "4772": "zapateria calzado marroquineria",
    "4773": "drogueria farmacia",
    "4791": "ecommerce ventas por internet tienda virtual redes",
    "4923": "camion transporte de carga fletes mudanzas",
    "4921": "taxi bus transporte de pasajeros conductor",
    "4520": "taller mecanica automotriz montallantas",
    "9602": "peluqueria barberia salon de belleza estetica manicure",
    "8621": "medico consultorio salud enfermera terapeuta",
    "8622": "odontologo dentista odontologia",
    "6910": "abogado juridico bufete derecho",
    "6920": "contador contabilidad revisor fiscal impuestos",
    "7110": "arquitecto ingeniero civil diseno de obra topografia",
    "7310": "publicidad marketing agencia community manager",
    "7410": "diseno grafico disenador ilustracion",
    "7420": "fotografia fotografo video",
    "4111": "constructor obra vivienda construccion",
    "4321": "electricista instalaciones electricas",
    "4330": "acabados pintura remodelacion enchape",
    "8521": "colegio profesor docente escuela primaria",
    "8543": "universidad docente universitario catedra",
    "8551": "cursos capacitacion academia formacion",
    "0141": "ganaderia finca ganado vacas leche",
    "0127": "cafe cacao cultivo finca cafetera",
    "5511": "hotel hospedaje hostal alojamiento",
    "8010": "vigilancia seguridad escolta celaduria",
    "8121": "aseo limpieza servicios generales",
    "6810": "arrendamiento inmuebles rentista finca raiz propiedad raiz",
    "6820": "inmobiliaria corretaje agente inmobiliario",
    "1081": "panaderia panadero reposteria pasteleria",
    "1410": "confeccion modisteria sastreria costura",
    "9511": "reparacion de computadores tecnico de sistemas",
}

# ---------------------------------------------------------------------------
# Catálogos operativos (valores por defecto, sobreescribibles por tenant)
# ---------------------------------------------------------------------------
CATALOGOS_OPERATIVOS_DEFAULTS: dict[str, list] = {
    "tipo_documento": [
        {"codigo": "CC", "etiqueta": "Cédula de ciudadanía"},
        {"codigo": "CE", "etiqueta": "Cédula de extranjería"},
        {"codigo": "PA", "etiqueta": "Pasaporte"},
        {"codigo": "PPT", "etiqueta": "Permiso por Protección Temporal"},
        {"codigo": "NIT", "etiqueta": "NIT"},
    ],
    "tipo_inmueble": [
        "Apartamento", "Casa", "Apartaestudio", "Local comercial", "Oficina",
        "Bodega", "Casa campestre", "Habitación",
    ],
    "tipo_contrato": [
        "Término indefinido", "Término fijo", "Obra o labor", "Prestación de servicios",
        "Aprendizaje SENA", "Ocasional",
    ],
    "situaciones_laborales": [
        "Empleado", "Independiente", "Empresario", "Pensionado", "Rentista de capital",
        "Contratista", "Estudiante", "Otro",
    ],
    "tipo_obligacion": [
        "Hipotecario", "Consumo", "Tarjeta de crédito", "Vehículo", "Libranza",
        "Educativo", "Microcrédito", "Otro",
    ],
    "estados_civiles": [
        "Soltero(a)", "Casado(a)", "Unión libre", "Separado(a)", "Divorciado(a)", "Viudo(a)",
    ],
    "parentescos": [
        "Cónyuge o compañero(a)", "Padre", "Madre", "Hijo(a)", "Hermano(a)", "Abuelo(a)",
        "Tío(a)", "Primo(a)", "Suegro(a)", "Amigo(a)", "Empleador", "Otro",
    ],
    "periodicidades": ["Mensual", "Quincenal"],
    "paises": [
        "Colombia", "Venezuela", "Ecuador", "Perú", "México", "Argentina", "Chile",
        "España", "Estados Unidos", "Otro",
    ],
}
