"""Configuracion por defecto del motor robusto: porte literal del ENGINE de Habitat
Risk (34 reglas, 6 grupos, v3.4). Sirve como semilla para la primera version
almacenada en la base de datos -- desde ahi se versiona igual que politicas_credito
(nunca se sobreescribe, se crea una fila nueva)."""
from motor_decision.robusto.schemas import MotorDecision, ParametrosMotor, ReglaMotor, VersionMotor

REGLAS_V3_4: list[ReglaMotor] = [
    # ---- CAPACIDAD DE PAGO ----
    ReglaMotor("R-CAP-01", "capacidad", "escala", 1, "cobertura", ">=", 3.0, 88, "Cobertura holgada",
               "El ingreso verificable ajustado cubre 3 o más veces el costo total de vivienda."),
    ReglaMotor("R-CAP-02", "capacidad", "escala", 2, "cobertura", ">=", 2.5, 78, "Cobertura suficiente",
               "Cobertura entre 2,5x y 3x."),
    ReglaMotor("R-CAP-03", "capacidad", "escala", 3, "cobertura", ">=", 2.0, 64, "Cobertura aceptable",
               "Cobertura entre 2x y 2,5x."),
    ReglaMotor("R-CAP-04", "capacidad", "escala", 4, "cobertura", ">=", 1.6, 42, "Cobertura ajustada",
               "Cobertura entre 1,6x y 2x: requiere análisis de flujo."),
    ReglaMotor("R-CAP-05", "capacidad", "escala", 5, "cobertura", ">=", 0, 15, "Cobertura insuficiente",
               "Cobertura inferior a 1,6x."),
    ReglaMotor("R-CAP-10", "capacidad", "ajuste", 10, "flujoPostArriendo", "<", 0, -22,
               "Flujo post-arriendo negativo",
               "Después de arriendo, obligaciones y gastos el flujo queda en negativo."),
    ReglaMotor("R-CAP-11", "capacidad", "ajuste", 11, "flujoPostArriendo", ">=", 1_500_000, 5,
               "Colchón de liquidez", "Flujo disponible post-arriendo superior a $1.500.000."),
    ReglaMotor("R-CAP-12", "capacidad", "ajuste", 12, "patrimonioNeto", ">=", 120_000_000, 4,
               "Respaldo patrimonial", "Patrimonio neto superior a $120.000.000."),
    # ---- ESTABILIDAD ----
    ReglaMotor("R-EST-01", "estabilidad", "escala", 1, "antiguedadMeses", ">=", 36, 90, "Antigüedad alta",
               "3 años o más en la actividad económica actual."),
    ReglaMotor("R-EST-02", "estabilidad", "escala", 2, "antiguedadMeses", ">=", 24, 78, "Antigüedad sólida",
               "Entre 2 y 3 años."),
    ReglaMotor("R-EST-03", "estabilidad", "escala", 3, "antiguedadMeses", ">=", 12, 64, "Antigüedad media",
               "Entre 1 y 2 años."),
    ReglaMotor("R-EST-04", "estabilidad", "escala", 4, "antiguedadMeses", ">=", 6, 44, "Antigüedad baja",
               "Entre 6 y 12 meses."),
    ReglaMotor("R-EST-05", "estabilidad", "escala", 5, "antiguedadMeses", ">=", 0, 22, "Antigüedad incipiente",
               "Menos de 6 meses."),
    ReglaMotor("R-EST-10", "estabilidad", "ajuste", 10, "contratoIndefinido", "=", 1, 6,
               "Contrato a término indefinido", "Vínculo laboral sin fecha de terminación."),
    ReglaMotor("R-EST-11", "estabilidad", "ajuste", 11, "ingresoPensional", "=", 1, 8,
               "Ingreso pensional vitalicio", "La mesada pensional es un ingreso estable y verificable."),
    ReglaMotor("R-EST-12", "estabilidad", "ajuste", 12, "contratoCorto", "=", 1, -12,
               "Vinculación por prestación de servicios",
               "Contrato con terminación cierta y renovación incierta."),
    # ---- ENDEUDAMIENTO ----
    ReglaMotor("R-END-01", "endeudamiento", "escala", 1, "ratioEndeudamiento", "<=", 0.15, 92,
               "Endeudamiento bajo", "Cuotas financieras hasta el 15% del ingreso."),
    ReglaMotor("R-END-02", "endeudamiento", "escala", 2, "ratioEndeudamiento", "<=", 0.25, 80,
               "Endeudamiento controlado", "Entre 15% y 25%."),
    ReglaMotor("R-END-03", "endeudamiento", "escala", 3, "ratioEndeudamiento", "<=", 0.35, 60,
               "Endeudamiento medio", "Entre 25% y 35%."),
    ReglaMotor("R-END-04", "endeudamiento", "escala", 4, "ratioEndeudamiento", "<=", 0.45, 36,
               "Endeudamiento alto", "Entre 35% y 45%."),
    ReglaMotor("R-END-05", "endeudamiento", "escala", 5, "ratioEndeudamiento", ">", 0.45, 12,
               "Endeudamiento crítico", "Cuotas superiores al 45% del ingreso."),
    ReglaMotor("R-END-10", "endeudamiento", "ajuste", 10, "obligacionesEnMora", "=", 1, -25,
               "Obligación en mora vigente", "Al menos una obligación reportada en mora."),
    # ---- VERIFICABILIDAD ----
    ReglaMotor("R-VER-01", "verificabilidad", "escala", 1, "verificabilidad", ">=", 90, 92,
               "Ingreso plenamente verificable", "90% o más del ingreso tiene soporte documental."),
    ReglaMotor("R-VER-02", "verificabilidad", "escala", 2, "verificabilidad", ">=", 75, 78,
               "Verificabilidad alta", "Entre 75% y 90%."),
    ReglaMotor("R-VER-03", "verificabilidad", "escala", 3, "verificabilidad", ">=", 60, 60,
               "Verificabilidad media", "Entre 60% y 75%."),
    ReglaMotor("R-VER-04", "verificabilidad", "escala", 4, "verificabilidad", ">=", 40, 38,
               "Verificabilidad baja", "Entre 40% y 60%: parte del ingreso no es bancarizado."),
    ReglaMotor("R-VER-05", "verificabilidad", "escala", 5, "verificabilidad", ">=", 0, 16,
               "Verificabilidad insuficiente", "Menos del 40% del ingreso es verificable."),
    ReglaMotor("R-VER-10", "verificabilidad", "ajuste", 10, "docsFaltantes", ">=", 2, -14,
               "Documentación incompleta", "Dos o más documentos obligatorios sin cargar."),
    # ---- HISTORIAL ----
    ReglaMotor("R-HIS-01", "historial", "escala", 1, "historialCodigo", "=", 3, 92,
               "Historial de arrendamiento positivo", "Arrendó antes sin mora ni procesos."),
    ReglaMotor("R-HIS-02", "historial", "escala", 2, "historialCodigo", "=", 2, 62,
               "Sin historial previo", "Primer arrendamiento: se evalúa neutral, no penaliza."),
    ReglaMotor("R-HIS-03", "historial", "escala", 3, "historialCodigo", "=", 1, 40,
               "Mora leve reportada", "Retrasos menores a 30 días en arriendos anteriores."),
    ReglaMotor("R-HIS-04", "historial", "escala", 4, "historialCodigo", "=", 0, 12,
               "Mora relevante o proceso de restitución", "Mora superior a 60 días o proceso jurídico."),
    # ---- FRAUDE (100 = sin señales) ----
    ReglaMotor("R-FRA-01", "fraude", "escala", 1, "alertasFraude", "=", 0, 95,
               "Sin señales de alerta", "No se detectaron inconsistencias documentales ni de identidad."),
    ReglaMotor("R-FRA-02", "fraude", "escala", 2, "alertasFraude", "=", 1, 60,
               "Una señal de alerta", "Una inconsistencia detectada: requiere verificación manual."),
    ReglaMotor("R-FRA-03", "fraude", "escala", 3, "alertasFraude", ">=", 2, 52,
               "Múltiples señales de alerta", "Dos o más inconsistencias: riesgo de fraude relevante."),
    ReglaMotor("R-FRA-10", "fraude", "ajuste", 10, "alertaIdentidad", "=", 1, -14,
               "Inconsistencia de identidad", "Los datos declarados no coinciden con el documento cargado."),
    ReglaMotor("R-FRA-11", "fraude", "ajuste", 11, "alertaIngresos", "=", 1, -18,
               "Ingresos declarados vs. extractos",
               "Diferencia superior al 25% entre lo declarado y lo bancarizado."),
]

HISTORIAL_VERSIONES = [
    VersionMotor("v3.4", "2026-06-01", "Camila Restrepo",
                 "Se elimina el rechazo automático por edad. Cobertura mínima baja de 3,0x a 2,0x con análisis de flujo.",
                 "Vigente", 37),
    VersionMotor("v3.3", "2026-03-15", "Andrés Villamil",
                 "Se incorpora el factor de verificabilidad de ingresos y el ajuste por documentación incompleta.",
                 "Archivada", 32),
    VersionMotor("v3.2", "2025-11-02", "Camila Restrepo",
                 "Ajuste de pesos: capacidad 30%, endeudamiento 20%. Se agrega grupo fraude.", "Archivada", 28),
    VersionMotor("v3.1", "2025-08-20", "Marcela Ospina",
                 "Primera versión con explicabilidad de factores en la decisión.", "Archivada", 24),
]

MOTOR_DEFAULT = MotorDecision(
    version="v3.4",
    vigente_desde="2026-06-01",
    autor="Camila Restrepo",
    pesos={"capacidad": 30, "estabilidad": 15, "endeudamiento": 20, "verificabilidad": 15, "historial": 10, "fraude": 10},
    parametros=ParametrosMotor(),
    reglas=REGLAS_V3_4,
    historial_versiones=HISTORIAL_VERSIONES,
)
